spring:
  datasource:
    username: root
    url: jdbc:mysql://192.168.1.7/sell?characterEncodeing=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jpa:
    show-sql: true