server:
  context-path: /sell
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.220.106:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #配置若为null则 不返回
  jackson:
    default-property-inclusion: non_null
#微信配置
wechat:
     mpAppId: wx137958ac7c70f66d
     mpAppSecret: db926844b47cbb18f91cce2da3eb7c24


