spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncodeing=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8081
  context-path: /sell